# Generated by Django 3.1.7 on 2021-03-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210301_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tansaction_id',
            new_name='transaction_id',
        ),
    ]
